export type ChartTimezone = {
  id: string;
  label: string;
  offset: string;
  abbrev?: string;
};

export const TIMEZONE_OPTIONS: ChartTimezone[] = [
  { id: 'Pacific/Honolulu', label: 'Honolulu', offset: '(UTC-10)' },
  { id: 'America/Anchorage', label: 'Anchorage', offset: '(UTC-9)' },
  { id: 'America/Los_Angeles', label: 'Los Angeles', offset: '(UTC-8)' },
  { id: 'America/Vancouver', label: 'Vancouver', offset: '(UTC-8)' },
  { id: 'America/Phoenix', label: 'Phoenix', offset: '(UTC-7)' },
  { id: 'America/Denver', label: 'Denver', offset: '(UTC-7)' },
  { id: 'America/Chicago', label: 'Chicago', offset: '(UTC-6)' },
  { id: 'America/Mexico_City', label: 'Mexico City', offset: '(UTC-6)' },
  { id: 'America/Bogota', label: 'Bogota', offset: '(UTC-5)' },
  { id: 'America/New_York', label: 'New York', offset: '(UTC-5)' },
  { id: 'America/Toronto', label: 'Toronto', offset: '(UTC-5)' },
  { id: 'America/Caracas', label: 'Caracas', offset: '(UTC-4)' },
  { id: 'America/Argentina/Buenos_Aires', label: 'Buenos Aires', offset: '(UTC-3)' },
  { id: 'America/Santiago', label: 'Santiago', offset: '(UTC-3)' },
  { id: 'America/Sao_Paulo', label: 'Sao Paulo', offset: '(UTC-3)' },
  { id: 'Atlantic/Azores', label: 'Azores', offset: '(UTC-1)' },
  { id: 'Europe/Dublin', label: 'Dublin', offset: '(UTC)' },
  { id: 'Europe/Lisbon', label: 'Lisbon', offset: '(UTC)' },
  { id: 'Europe/London', label: 'London', offset: '(UTC)' },
  { id: 'Atlantic/Reykjavik', label: 'Reykjavik', offset: '(UTC)' },
  { id: 'Europe/Amsterdam', label: 'Amsterdam', offset: '(UTC+1)' },
  { id: 'Europe/Belgrade', label: 'Belgrade', offset: '(UTC+1)' },
  { id: 'Europe/Berlin', label: 'Berlin', offset: '(UTC+1)' },
  { id: 'Europe/Bratislava', label: 'Bratislava', offset: '(UTC+1)' },
  { id: 'Europe/Brussels', label: 'Brussels', offset: '(UTC+1)' },
  { id: 'Europe/Budapest', label: 'Budapest', offset: '(UTC+1)' },
  { id: 'Africa/Casablanca', label: 'Casablanca', offset: '(UTC+1)' },
  { id: 'Europe/Copenhagen', label: 'Copenhagen', offset: '(UTC+1)' },
  { id: 'Africa/Lagos', label: 'Lagos', offset: '(UTC+1)' },
  { id: 'Europe/Luxembourg', label: 'Luxembourg', offset: '(UTC+1)' },
  { id: 'Europe/Madrid', label: 'Madrid', offset: '(UTC+1)' },
  { id: 'Europe/Malta', label: 'Malta', offset: '(UTC+1)' },
  { id: 'Europe/Oslo', label: 'Oslo', offset: '(UTC+1)' },
  { id: 'Europe/Paris', label: 'Paris', offset: '(UTC+1)' },
  { id: 'Europe/Rome', label: 'Rome', offset: '(UTC+1)' },
  { id: 'Europe/Stockholm', label: 'Stockholm', offset: '(UTC+1)' },
  { id: 'Europe/Vienna', label: 'Vienna', offset: '(UTC+1)' },
  { id: 'Europe/Warsaw', label: 'Warsaw', offset: '(UTC+1)' },
  { id: 'Europe/Zurich', label: 'Zurich', offset: '(UTC+1)' },
  { id: 'Europe/Athens', label: 'Athens', offset: '(UTC+2)' },
  { id: 'Africa/Cairo', label: 'Cairo', offset: '(UTC+2)' },
  { id: 'Europe/Helsinki', label: 'Helsinki', offset: '(UTC+2)' },
  { id: 'Asia/Jerusalem', label: 'Jerusalem', offset: '(UTC+2)' },
  { id: 'Africa/Johannesburg', label: 'Johannesburg', offset: '(UTC+2)' },
  { id: 'Europe/Riga', label: 'Riga', offset: '(UTC+2)' },
  { id: 'Europe/Sofia', label: 'Sofia', offset: '(UTC+2)' },
  { id: 'Europe/Tallinn', label: 'Tallinn', offset: '(UTC+2)' },
  { id: 'Europe/Vilnius', label: 'Vilnius', offset: '(UTC+2)' },
  { id: 'Asia/Bahrain', label: 'Bahrain', offset: '(UTC+3)' },
  { id: 'Europe/Istanbul', label: 'Istanbul', offset: '(UTC+3)' },
  { id: 'Asia/Kuwait', label: 'Kuwait', offset: '(UTC+3)' },
  { id: 'Europe/Moscow', label: 'Moscow', offset: '(UTC+3)' },
  { id: 'Asia/Qatar', label: 'Qatar', offset: '(UTC+3)' },
  { id: 'Asia/Riyadh', label: 'Riyadh', offset: '(UTC+3)' },
  { id: 'Asia/Tehran', label: 'Tehran', offset: '(UTC+3:30)' },
  { id: 'Asia/Dubai', label: 'Dubai', offset: '(UTC+4)' },
  { id: 'Asia/Muscat', label: 'Muscat', offset: '(UTC+4)' },
  { id: 'Asia/Kolkata', label: 'Kolkata', offset: '(UTC+5:30)' },
  { id: 'Asia/Bangkok', label: 'Bangkok', offset: '(UTC+7)' },
  { id: 'Asia/Jakarta', label: 'Jakarta', offset: '(UTC+7)' },
  { id: 'Asia/Hong_Kong', label: 'Hong Kong', offset: '(UTC+8)' },
  { id: 'Asia/Manila', label: 'Manila', offset: '(UTC+8)' },
  { id: 'Asia/Shanghai', label: 'Shanghai', offset: '(UTC+8)' },
  { id: 'Asia/Singapore', label: 'Singapore', offset: '(UTC+8)' },
  { id: 'Asia/Taipei', label: 'Taipei', offset: '(UTC+8)' },
  { id: 'Asia/Tokyo', label: 'Tokyo', offset: '(UTC+9)' },
  { id: 'Asia/Seoul', label: 'Seoul', offset: '(UTC+9)' },
  { id: 'Australia/Brisbane', label: 'Brisbane', offset: '(UTC+10)' },
  { id: 'Australia/Sydney', label: 'Sydney', offset: '(UTC+10)' },
  { id: 'Pacific/Auckland', label: 'Auckland', offset: '(UTC+12)' },
  { id: 'Pacific/Chatham', label: 'Chatham', offset: '(UTC+12:45)' },
  { id: 'Pacific/Fakaofo', label: 'Tokelau', offset: '(UTC+13)' },
];

export const getTimezoneById = (id: string) =>
  TIMEZONE_OPTIONS.find((tz) => tz.id === id) || TIMEZONE_OPTIONS[0];
